version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: dockerfile.dev
    container_name: dev_container
  prod:
    build:
      context: .
      dockerfile: dockerfile.prod
    container_name: prod_container
  staging:
    build:
      context: .
      dockerfile: dockerfile.staging
    container_name: staging_container