FROM ubuntu:latest 

LABEL name="raviteja"

ENV AWS_ACCESS_KEY_ID=kjdnvjnjksnajvn\
    AWS_SECRET_KEY_ID=kcnsdmkkjs\
    AWS_DEFAULT_REGION=US-EAST-1A

ARG T_VERSION='1.7.5' \
    P_VERSION='1.10.1'

RUN apt update && apt install -y jq net-tools curl wget unzip \
    && apt install -y nginx iputils-ping

RUN wget https://releases.hashicorp.com/terraform/${T_VERSION}/terraform_${T_VERSION}_linux_amd64.zip \
    && wget https://releases.hashicorp.com/packer/${P_VERSION}/packer_${P_VERSION}_linux_amd64.zip\
    && unzip terraform_${T_VERSION}_linux_amd64.zip  && unzip packer_${P_VERSION}_linux_amd64.zip\
    && chmod 777 terraform && chmod 777 packer\
    && ./terraform version && ./packer version 
CMD ["nginx","-g","daemon off;"]


